// Code generated by "stringer -type=TextTemplate"; DO NOT EDIT.

package help

import "strconv"

const _TextTemplate_name = "EmailAfterRegistrationEmailNotificationEmailPaymentCancelEmailPaymentPleaseEmailValidationFileMetaSyncMetaGuiEmailRequiredGuiInfoGuiPassRequiredGuiPitchGuiTosHtmlLinkErrorHtmlLinkExpiredHtmlVerificationOkHtmlWaitPaypalTokenMetaProfileAllHelpEmailQuotaLeft"

var _TextTemplate_index = [...]uint8{0, 22, 39, 57, 75, 90, 98, 106, 122, 129, 144, 152, 158, 171, 186, 204, 218, 227, 234, 241, 255}

func (i TextTemplate) String() string {
	if i < 0 || i >= TextTemplate(len(_TextTemplate_index)-1) {
		return "TextTemplate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TextTemplate_name[_TextTemplate_index[i]:_TextTemplate_index[i+1]]
}
